### ISSUE TITLE
How to become an assistant.

### ISSUE THREAD

**Issue by RamasyaR** [zhanglongqi/python-sdbus-modemmanager#1]
Hello, I am interested in your project and I have time and opportunity to develop it. First of all, I'm interested in voice calls and everything connected with them, I have some developments and corrections in this area. How to make changes to your project. My mail is radikot88@gmail.com.

**Comment by zhanglongqi** [comment]
I don't know too much about voice calls. That'll be great if you can contribute more. I basically follow the `python-sdbus-network` folder structure and only some formating style is a little different.

you can fork and work on it. you can pull request if you reach a certain stage. No need to implement all the functions at once but make sure it is a working stage before you make the pull request.

the python style I use:

```json
	"python.formatting.provider": "yapf",
	"python.formatting.yapfArgs": [
		"--style",
		"{USE_TABS=true,COLUMN_LIMIT=180,CONTINUATION_ALIGN_STYLE='VALIGN-RIGHT'}"
	],
```
