### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by gotthardp** [zhanglongqi/python-sdbus-modemmanager#5]
Hello and thank you for such a nice project. Would you please declare which open-source license applies to it? It cannot be used without a license.

It is perfectly sufficient just to add some `COPYING` file to the main directory, just like the python-sdbus itself or its bindings did (e.g. https://github.com/bernhardkaindl/python-sdbus-systemd). You may also want to declare a license in the `setup.py` (`license` and `classifiers` parameters).

**Comment by zhanglongqi** [comment]
done
